### PR TITLE
autovizwidget 0.20.0

### PR DESCRIPTION
**Pull request by skupr-anaconda**
License: https://github.com/jupyter-incubator/sparkmagic/blob/master/autovizwidget/LICENSE.md
Requirements: 
- https://github.com/jupyter-incubator/sparkmagic/blob/0.20.0/autovizwidget/requirements.txt
- https://github.com/jupyter-incubator/sparkmagic/blob/0.20.0/autovizwidget/setup.py

Actions:
1. Add a license file to the recipe
2. Remove `noarch`
3. Skip `py<37`
4. Reorder `run` dependencies
5. Update `test/imports`
6. Add `pip check`
7. Update `home` url
8. Add `license_family`, `license_file`, `license_url`
9. Add `dev_url`

### CODE REVIEW

**Comment by skupr-anaconda** [comment]
Waiting for https://github.com/AnacondaRecipes/hdijupyterutils-feedstock/pull/2

**Review by varlackc — COMMENTED** [review]
We need to add the `doc_url`

**Comment by skupr-anaconda** [comment]
> We need to add the `doc_url`

@varlackc This package hasn't `doc_url` because it's a submodule of `sparkmagic` https://github.com/jupyter-incubator/sparkmagic

**Review by varlackc — APPROVED** [review]
LGTM

**Review by varlackc — APPROVED** [review]
LGTM

**Pull request merged**
